### ISSUE TITLE
Add column names

### ISSUE THREAD

**Issue by PaulKovalov** [googleinterns/step257-2020#108]
Add ability to give a column a name

**Comment by NeilLi1992** [comment]
Let's make the name optional & editable.

**Comment by PaulKovalov** [comment]
@NeilLi1992 are we going to have names for rows as well?

**Comment by NeilLi1992** [comment]
> @NeilLi1992 are we going to have names for rows as well?

If it doesn't make it significantly more complex, I think we should do this as well.
